import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/custom/AppSidebar";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/hooks/use-auth";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Starbucks Clone",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-green-50 max-w-[1440px] mx-auto`}
            // style={{ background: 'radial-gradient(circle, hsla(29, 54%, 83%, 1) 0%, hsla(0, 0%, 99%, 1) 100%)'}}
        >
        <Toaster position="top-center" richColors={false} />
        <AuthProvider>
            <SidebarProvider className="text-black">
                <AppSidebar />
                    <main className="w-full py-4 px-2">
                    {/* <SidebarTrigger className="text-black" /> */}
                    {children}
                </main>
            </SidebarProvider>
        </AuthProvider>
        </body>
        </html>
    );
}
